import {
  IconCircleCheck,
  IconCreditCard,
  IconExternalLink,
  IconLoader2,
  IconQrcode,
  IconRefresh,
  IconX,
} from '@tabler/icons-react';
import { QRCodeSVG } from 'qrcode.react';
import { useCallback, useEffect, useRef, useState } from 'react';

import {
  getPaymentServiceResultMessage,
  type PaymentDetailDto,
  type PayOsPaymentLinkResponseDto,
  type SePayVietQrResponseDto,
} from '@/services/api/payments';
import {
  useCreatePayOsPaymentLink,
  useGenerateSePayVietQr,
  usePaymentDetail,
  usePaymentRealtime,
} from '@/services/queries';

import './PaymentCollectionModal.css';

type MessageTone = 'success' | 'error' | 'info';

type PaymentMethodKey = 'SEPAY' | 'PAYOS';

const paymentMethodOptions: Array<{
  id: PaymentMethodKey;
  label: string;
  description: string;
  icon: typeof IconQrcode;
}> = [
  { id: 'SEPAY', label: 'SePay VietQR', description: 'Scan QR with any banking app', icon: IconQrcode },
  { id: 'PAYOS', label: 'PayOS Checkout', description: 'Card, e-wallet or bank QR', icon: IconCreditCard },
];

type PaymentCollectionModalProps = {
  payment: PaymentDetailDto | null;
  title?: string;
  completionTitle?: string;
  completionDescription?: string;
  continueLabel?: string;
  onClose: () => void;
  onContinue?: (payment: PaymentDetailDto) => void;
  onPaid?: (payment: PaymentDetailDto) => void;
};

export function PaymentCollectionModal({
  payment,
  title = 'Collect Payment',
  completionTitle = 'Payment completed',
  completionDescription = 'The payment has been confirmed. You can continue to the next step.',
  continueLabel = 'Continue',
  onClose,
  onContinue,
  onPaid,
}: Readonly<PaymentCollectionModalProps>) {
  const paymentId = payment?.paymentId;
  const [activeMethod, setActiveMethod] = useState<PaymentMethodKey>('SEPAY');
  const [sePayQr, setSePayQr] = useState<SePayVietQrResponseDto | null>(null);
  const [payOsLink, setPayOsLink] = useState<PayOsPaymentLinkResponseDto | null>(null);
  const [message, setMessage] = useState('');
  const [messageTone, setMessageTone] = useState<MessageTone>('info');
  const autoGeneratedPaymentIdRef = useRef<string | null>(null);
  const paymentQuery = usePaymentDetail(paymentId, { enabled: Boolean(paymentId) });
  const generateQrMutation = useGenerateSePayVietQr();
  const createPayOsLinkMutation = useCreatePayOsPaymentLink();
  const currentPayment = paymentQuery.data ?? payment;
  const currentStatus = normalizePaymentStatus(currentPayment?.status);
  const isCollectable = isCollectablePaymentStatus(currentStatus);
  const isPaid = isPaidPaymentStatus(currentStatus) || isFullyPaidByAmounts(currentPayment);
  const isTerminalUncollectable = isTerminalUncollectablePaymentStatus(currentStatus);

  usePaymentRealtime({
    paymentId,
    enabled: Boolean(paymentId),
    onPaymentUpdated: (payload) => {
      const nextStatus = normalizePaymentStatus(payload.status);
      const settledAsPaid = isPaidPaymentStatus(nextStatus) || payload.remainingAmount <= 0;

      if (settledAsPaid) {
        setMessage('');
        void paymentQuery.refetch().then((result) => {
          if (result.data) {
            onPaid?.(result.data);
          }
        });
        return;
      }

      setMessageTone('info');
      setMessage(`Payment ${formatStatusLabel(nextStatus)}. Latest paid amount: ${formatMoney(payload.paidAmount, currentPayment?.currency)}.`);
    },
  });

  const handleGenerateQr = useCallback(async () => {
    if (!paymentId) return;

    setMessage('');
    setMessageTone('info');

    try {
      const result = await generateQrMutation.mutateAsync(paymentId);
      setSePayQr(result);
      setMessageTone('success');
    } catch (error) {
      setMessageTone('error');
      setMessage(getPaymentServiceResultMessage(error));
    }
  }, [generateQrMutation, paymentId]);

  const handleCreatePayOsLink = useCallback(async () => {
    if (!paymentId) return;

    setMessage('');
    setMessageTone('info');

    try {
      const result = await createPayOsLinkMutation.mutateAsync({
        paymentId,
        returnUrl: window.location.href,
        cancelUrl: window.location.href,
      });
      setPayOsLink(result);
      setMessageTone('success');
    } catch (error) {
      setMessageTone('error');
      setMessage(getPaymentServiceResultMessage(error));
    }
  }, [createPayOsLinkMutation, paymentId]);

  function handleSelectMethod(method: PaymentMethodKey) {
    setActiveMethod(method);
    setMessage('');
    setMessageTone('info');
  }

  useEffect(() => {
    setActiveMethod('SEPAY');
    setSePayQr(null);
    setPayOsLink(null);
    setMessage('');
    setMessageTone('info');
    autoGeneratedPaymentIdRef.current = null;
  }, [paymentId]);

  useEffect(() => {
    if (!paymentId || activeMethod !== 'SEPAY' || !isCollectable || isPaid) return;
    if (autoGeneratedPaymentIdRef.current === paymentId) return;

    autoGeneratedPaymentIdRef.current = paymentId;
    void handleGenerateQr();
  }, [activeMethod, handleGenerateQr, isCollectable, isPaid, paymentId]);

  if (!currentPayment) {
    return null;
  }

  return (
    <div className="payment-modal-overlay">
      <section className="payment-modal" role="dialog" aria-modal="true" aria-labelledby="payment-modal-title">
        <header className="payment-modal-header">
          <div>
            <h3 id="payment-modal-title">{title}</h3>
            <p>{currentPayment.paymentCode}</p>
          </div>
          <button aria-label="Close payment modal" type="button" onClick={onClose}>
            <IconX size={18} />
          </button>
        </header>

        <PaymentStatusRow
          isRefreshing={paymentQuery.isFetching}
          status={currentStatus}
          onRefresh={() => void paymentQuery.refetch()}
        />

        {!isPaid && isCollectable ? (
          <>
            <PaymentMethodSwitch activeMethod={activeMethod} onSelect={handleSelectMethod} />

            <div className="payment-collection-layout">
              <aside className="payment-info-column">
                <div className="payment-summary-stack">
                  <SummaryItem label="Amount" value={formatMoney(currentPayment.amount, currentPayment.currency)} />
                  <SummaryItem label="Type" value={formatStatusLabel(normalizePaymentType(currentPayment.paymentType))} />
                </div>

                {activeMethod === 'SEPAY' && sePayQr ? (
                  <TransferDetails
                    items={[
                      { label: 'Transfer Content', value: sePayQr.transferContent },
                      { label: 'Account', value: sePayQr.accountNo },
                    ]}
                  />
                ) : null}

                {activeMethod === 'PAYOS' && payOsLink ? (
                  <TransferDetails
                    items={[
                      { label: 'Order Code', value: String(payOsLink.orderCode) },
                      { label: 'Provider', value: 'PayOS - Payment Link' },
                    ]}
                  />
                ) : null}
              </aside>

              {activeMethod === 'SEPAY' ? (
                <SePayPanel qr={sePayQr} isGenerating={generateQrMutation.isPending} />
              ) : (
                <PayOsPanel
                  currency={currentPayment.currency}
                  isCreating={createPayOsLinkMutation.isPending}
                  link={payOsLink}
                  onCreateLink={() => void handleCreatePayOsLink()}
                />
              )}
            </div>
          </>
        ) : (
          <div className="payment-summary-grid">
            <SummaryItem label="Amount" value={formatMoney(currentPayment.amount, currentPayment.currency)} />
            <SummaryItem label="Type" value={formatStatusLabel(normalizePaymentType(currentPayment.paymentType))} />
          </div>
        )}

        {isPaid ? (
          <PaymentCompletePanel
            completionDescription={completionDescription}
            completionTitle={completionTitle}
            continueLabel={continueLabel}
            payment={currentPayment}
            onClose={onClose}
            onContinue={onContinue}
          />
        ) : null}

        {!isPaid && isTerminalUncollectable ? (
          <p className="payment-modal-note">This payment is not collectable in its current status.</p>
        ) : null}

        {isPaid ? null : <PaymentModalMessage message={message} tone={messageTone} />}
      </section>
    </div>
  );
}

function PaymentStatusRow({
  isRefreshing,
  status,
  onRefresh,
}: Readonly<{ isRefreshing: boolean; status: string; onRefresh: () => void }>) {
  return (
    <div className="payment-modal-status-row">
      <span className={`payment-status-badge payment-status-${status.toLowerCase()}`}>{formatStatusLabel(status)}</span>
      <button disabled={isRefreshing} type="button" onClick={onRefresh}>
        <IconRefresh size={16} />
        <span>{isRefreshing ? 'Refreshing...' : 'Refresh'}</span>
      </button>
    </div>
  );
}

function PaymentCompletePanel({
  completionDescription,
  completionTitle,
  continueLabel,
  payment,
  onClose,
  onContinue,
}: Readonly<{
  completionDescription: string;
  completionTitle: string;
  continueLabel: string;
  payment: PaymentDetailDto;
  onClose: () => void;
  onContinue?: (payment: PaymentDetailDto) => void;
}>) {
  return (
    <section className="payment-complete-panel">
      <IconCircleCheck size={44} />
      <div>
        <h4>{completionTitle}</h4>
        <p>{completionDescription}</p>
      </div>
      <button type="button" onClick={() => (onContinue ? onContinue(payment) : onClose())}>
        {continueLabel}
      </button>
    </section>
  );
}

function PaymentModalMessage({ message, tone }: Readonly<{ message: string; tone: MessageTone }>) {
  if (!message) {
    return null;
  }

  return (
    <p className={tone === 'error' ? 'payment-modal-message payment-modal-message-error' : 'payment-modal-message'}>
      {message}
    </p>
  );
}

function SummaryItem({ label, value }: Readonly<{ label: string; value: string }>) {
  return (
    <div className="payment-summary-item">
      <span>{label}</span>
      <strong>{value}</strong>
    </div>
  );
}

function PaymentMethodSwitch({
  activeMethod,
  onSelect,
}: Readonly<{ activeMethod: PaymentMethodKey; onSelect: (method: PaymentMethodKey) => void }>) {
  return (
    <div className="payment-method-switch" role="tablist" aria-label="Payment method">
      {paymentMethodOptions.map(({ id, label, description, icon: MethodIcon }) => (
        <button
          key={id}
          aria-selected={activeMethod === id}
          className={activeMethod === id ? 'payment-method-tab payment-method-tab-active' : 'payment-method-tab'}
          role="tab"
          type="button"
          onClick={() => onSelect(id)}
        >
          <span className="payment-method-tab-icon">
            <MethodIcon size={18} stroke={2} />
          </span>
          <span className="payment-method-tab-copy">
            <strong>{label}</strong>
            <small>{description}</small>
          </span>
        </button>
      ))}
    </div>
  );
}

function TransferDetails({ items }: Readonly<{ items: Array<{ label: string; value: string }> }>) {
  return (
    <dl className="payment-transfer-details">
      {items.map(({ label, value }) => (
        <div key={label}>
          <dt>{label}</dt>
          <dd>{value}</dd>
        </div>
      ))}
    </dl>
  );
}

function SePayPanel({ qr, isGenerating }: Readonly<{ qr: SePayVietQrResponseDto | null; isGenerating: boolean }>) {
  return (
    <section className="payment-qr-panel">
      <div className="payment-qr-panel-heading">
        <IconQrcode size={20} />
        <div>
          <h4>SePay VietQR</h4>
          <p>{isGenerating ? 'Generating transfer QR...' : 'Scan this QR to pay the remaining amount.'}</p>
        </div>
      </div>

      <div className="payment-qr-display">
        {qr ? (
          <img src={qr.vietQrUrl} alt={`VietQR for ${qr.paymentCode}`} />
        ) : (
          <div className="payment-qr-placeholder">
            <IconQrcode size={42} />
            <span>{isGenerating ? 'Generating QR...' : 'QR will appear here automatically.'}</span>
          </div>
        )}
      </div>
    </section>
  );
}

function PayOsPanel({
  currency,
  isCreating,
  link,
  onCreateLink,
}: Readonly<{
  currency: string;
  isCreating: boolean;
  link: PayOsPaymentLinkResponseDto | null;
  onCreateLink: () => void;
}>) {
  const qr = resolvePayOsQr(link?.qrCode);

  return (
    <section className="payment-qr-panel">
      <div className="payment-qr-panel-heading">
        <IconCreditCard size={20} />
        <div>
          <h4>PayOS Checkout</h4>
          <p>{getPayOsPanelDescription(isCreating, Boolean(qr))}</p>
        </div>
      </div>

      <div className="payment-qr-display">
        {link ? (
          <div className="payment-payos-result">
            {qr?.kind === 'image' ? <img src={qr.src} alt={`PayOS QR for ${link.paymentCode}`} /> : null}

            {qr?.kind === 'payload' ? (
              <div className="payment-payos-qr">
                <QRCodeSVG level="M" size={240} title={`PayOS VietQR for ${link.paymentCode}`} value={qr.value} />
              </div>
            ) : null}

            <p className="payment-payos-amount">{formatMoney(link.amount, currency)}</p>

            <div className="payment-payos-actions">
              <a className="payment-payos-action" href={link.checkoutUrl} target="_blank" rel="noreferrer">
                <IconExternalLink size={16} stroke={2} />
                <span>Open PayOS Checkout</span>
              </a>
              <button
                className="payment-payos-action payment-payos-action-ghost"
                disabled={isCreating}
                type="button"
                onClick={onCreateLink}
              >
                {isCreating ? (
                  <IconLoader2 className="payment-modal-spinner" size={16} stroke={2} />
                ) : (
                  <IconRefresh size={16} stroke={2} />
                )}
                <span>{isCreating ? 'Creating...' : 'New Link'}</span>
              </button>
            </div>
          </div>
        ) : (
          <div className="payment-qr-placeholder">
            <IconCreditCard size={42} />
            <span>{isCreating ? 'Creating payment link...' : 'Create a PayOS payment link to continue.'}</span>
            <button className="payment-payos-action" disabled={isCreating} type="button" onClick={onCreateLink}>
              {isCreating ? (
                <IconLoader2 className="payment-modal-spinner" size={16} stroke={2} />
              ) : (
                <IconCreditCard size={16} stroke={2} />
              )}
              <span>{isCreating ? 'Creating...' : 'Generate QR Code'}</span>
            </button>
          </div>
        )}
      </div>
    </section>
  );
}

/** Matches backend PaymentStatus enum ordinals (see services/api/payments.ts). */
const paymentStatusByNumber: Record<number, string> = {
  0: 'PENDING',
  1: 'PROCESSING',
  2: 'PAID',
  3: 'FAILED',
  4: 'CANCELLED',
  5: 'EXPIRED',
  6: 'REFUNDED',
};

const paymentTypeByNumber: Record<number, string> = {
  0: 'PROJECT_START_FEE',
  1: 'DEPOSIT',
  2: 'REMAINING_PAYMENT',
  3: 'LEGACY_FULL_PAYMENT',
  4: 'LEGACY_REFUND',
  5: 'LEGACY_OTHER',
};

function getPayOsPanelDescription(isCreating: boolean, hasQr: boolean) {
  if (isCreating) return 'Creating a secure payment link...';
  if (hasQr) return 'Scan this QR with your banking app, or open the PayOS checkout page.';

  return 'Open the PayOS checkout page to pay by card, e-wallet or bank QR.';
}

type PayOsQrSource = { kind: 'image'; src: string } | { kind: 'payload'; value: string } | null;

/** PayOS returns either a ready-made image URL or a raw VietQR payload that must be encoded client-side. */
function resolvePayOsQr(qrCode?: string | null): PayOsQrSource {
  const trimmed = qrCode?.trim();

  if (!trimmed) return null;

  if (/^(https?:\/\/|data:image\/)/i.test(trimmed)) {
    return { kind: 'image', src: trimmed };
  }

  return { kind: 'payload', value: trimmed };
}

function isCollectablePaymentStatus(status?: string | null) {
  return status === 'PENDING' || status === 'PROCESSING';
}

function isPaidPaymentStatus(status?: string | null) {
  return status === 'PAID';
}

function isTerminalUncollectablePaymentStatus(status?: string | null) {
  return status === 'FAILED' || status === 'CANCELLED' || status === 'EXPIRED' || status === 'REFUNDED';
}

function isFullyPaidByAmounts(payment?: PaymentDetailDto | null) {
  if (!payment) return false;

  if (typeof payment.remainingAmount === 'number' && payment.remainingAmount <= 0) {
    return true;
  }

  return typeof payment.paidAmount === 'number' && payment.paidAmount >= payment.amount && payment.amount > 0;
}

function normalizePaymentStatus(value: unknown) {
  return normalizeLegacyPaymentEnum(normalizeEnumValue(value, paymentStatusByNumber, 'PENDING'));
}

function normalizePaymentType(value: unknown) {
  return normalizeLegacyPaymentEnum(normalizeEnumValue(value, paymentTypeByNumber, 'UNKNOWN_PAYMENT_TYPE'));
}

function normalizeLegacyPaymentEnum(value: string) {
  // Older payloads used PARTIALLY_PAID; current API settles full charges as PAID.
  if (value === 'PARTIALLY_PAID' || value === 'LEGACY_PARTIALLY_PAID') return 'PAID';
  if (value === 'FULL_PAYMENT') return 'LEGACY_FULL_PAYMENT';
  if (value === 'REFUND') return 'LEGACY_REFUND';
  if (value === 'OTHER') return 'LEGACY_OTHER';

  return value;
}

function normalizeEnumValue(value: unknown, numberMap: Record<number, string>, fallback: string) {
  if (typeof value === 'string') {
    const trimmed = value.trim();
    const numeric = Number(trimmed);

    if (trimmed && Number.isInteger(numeric) && numeric in numberMap) {
      return numberMap[numeric];
    }

    return trimmed ? trimmed.toUpperCase() : fallback;
  }

  if (typeof value === 'number' && Number.isInteger(value) && value in numberMap) {
    return numberMap[value];
  }

  if (value && typeof value === 'object') {
    const candidate = value as { name?: unknown; value?: unknown; status?: unknown };

    return normalizeEnumValue(candidate.name ?? candidate.value ?? candidate.status, numberMap, fallback);
  }

  return fallback;
}

function formatMoney(value?: number | null, currency = 'VND') {
  return new Intl.NumberFormat('vi-VN', {
    style: 'currency',
    currency: currency || 'VND',
    maximumFractionDigits: 0,
  }).format(value ?? 0);
}

function formatStatusLabel(value?: string | null) {
  if (!value) return '-';

  return value
    .toLowerCase()
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}
